config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout

  get 'revoke_client' => 'clients#revoke', as: :revoke_client
  get 'reactivate_client' => 'clients#reactivate', as: :reactivate_client

  resources :clients, only: [:index, :create, :new, :destroy]
  resources :events, only: [:index, :create, :new, :destroy]
  resources :users, only: [:create, :new, :update]
  resources :admins, only: [:index]

  # API routes
  namespace :api do
    namespace :v1 do
      post '/auth' => 'sessions#auth'

      resources :salaries, only: [:index, :show, :create, :update, :destroy] do
        resources :tags, only: [:index]
        resources :locations, only: [:index]
      end

      resources :tags, only: [:index, :show, :create] do
        resources :salaries, only: [:index]
      end

      resources :locations, only: [:index, :show, :create] do
        resources :salaries, only: [:index]
      end

      resources :resource_owners, only: [:index, :show, :create] do
        resources :salaries, only: [:index]
      end
    end
  end
end

app/views/admins/index.html.erb
<h1>Admin</h1>
<div>
  <h2>Registrerade applikationer</h2>
  <ul id="user-clients">
    <% @clients.each do |client| %>
      <li>
        <h3><%= client.name %></h3>
        <p><strong>Användare:</strong> <%= client.user.username %></p>
        <p><strong>API-nyckel:</strong> <%= client.key %></p>

        <% if client.active %>
          <p class="active"><strong>Status: </strong>Aktiv</p>
        <% else %>
          <p class="inactive"><strong>Status: </strong>Inaktiverad av admin</p>
        <% end %>

        <p><strong>Url:</strong> <%= client.url %></p>
        <p><strong>Beskrivning:</strong> <%= client.description %></p>

        <% if client.active %>
          <%= link_to 'Inaktivera', revoke_client_path(id: client.id) %>
        <% else %>
          <%= link_to 'Återaktivera', reactivate_client_path(id: client.id) %>
        <% end %>
        <br/>
        <%= link_to "Ta bort (går inte att ångra)", client, method: :delete %>
      </li>
    <% end %>
  </ul>
</div>