config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout

  get 'revoke_client' => 'clients#revoke', as: :revoke_client
  get 'reactivate_client' => 'clients#reactivate', as: :reactivate_client

  resources :clients, only: [:index, :create, :new, :destroy]
  resources :events, only: [:index, :create, :new, :destroy]
  resources :users, only: [:create, :new, :update]
  resources :admins, only: [:index]

  # API routes
  namespace :api do
    namespace :v1 do
      post '/auth' => 'sessions#auth'

      resources :salaries, only: [:index, :show, :create, :update, :destroy] do
        resources :tags, only: [:index]
        resources :locations, only: [:index]
      end

      resources :tags, only: [:index, :show, :create] do
        resources :salaries, only: [:index]
      end

      resources :locations, only: [:index, :show, :create] do
        resources :salaries, only: [:index]
      end

      resources :resource_owners, only: [:index, :show, :create] do
        resources :salaries, only: [:index]
      end
    end
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 250 }
  belongs_to :user

  before_create :generate_key

  def generate_key
    loop do
      self.key = SecureRandom.base64(20)
      break unless Client.find_by(key: key)
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :require_login
  before_action :fetch_client, only: [:destroy, :revoke, :reactivate]

  def index
    @user = User.find(session[:userid])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    @client.user_id = session[:userid]

    if @client.save
      flash[:success] = 'Applikationen sparades.'
      redirect_to clients_path
    else
      flash[:danger] = 'Applikationen kunde inte sparas.'
      render :new
    end
  end

  def destroy
    @client.destroy
    flash[:success] = 'Applikationen raderades.'
    if current_user.role_id == 2
      redirect_to admins_path
    else
      redirect_to clients_path
    end
  end

  def revoke
    @client.active = false
    @client.save
    flash[:success] = 'Applikationen har inaktiverats.'
    redirect_to admins_path
  end

  def reactivate
    @client.active = true
    @client.save
    flash[:success] = 'Applikationen har återaktiverats.'
    redirect_to admins_path
  end

  private

  def client_params
    params.require(:client).permit(:name, :description, :url)
  end

  def fetch_client
    @client = Client.find(params[:id])
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/index.html.erb
<h1>Applikationer</h1>
  <div>
  <%= link_to 'Lägg till applikation', new_client_path, :id => 'add-client' %>
  <ul id="user-clients">
    <% @user.clients.each do |client| %>
      <li>
          <h2><%= client.name %></h2>
          <p><strong>API-nyckel:</strong> <%= client.key %></p>

          <% if client.active %>
            <p class="active"><strong>Status: </strong>Aktiv</p>
          <% else %>
            <p class="inactive"><strong>Status: </strong>Inaktiverad av admin</p>
          <% end %>

          <p><strong>Url:</strong> <%= client.url %></p>
          <p><strong>Beskrivning:</strong> <%= client.description %></p>
          <%= link_to "Ta bort (går inte att ångra)", client, method: :delete %>
      </li>
    <% end %>
  </ul>
</div>

app/views/clients/new.html.erb
<div id="register-client">
  <h1>Lägg till applikation</h1>
  <fieldset>
    <%= form_for @client do |c| %>
      <%= c.label 'Namn (max 50 tecken)', :for => 'client_name' %>
      <%= c.text_field :name %>
      <%= c.label 'Beskrivning (max 250 tecken)', :for => 'client_description' %>
      <%= c.text_area :description %>
      <%= c.label :url %>
      <%= c.url_field :url %>
      <%= c.submit 'Skapa', id: "submit" %>
    <% end %>
  </fieldset>
  <%= link_to 'Tillbaka till min sida', clients_path %>
</div>