config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout

  get 'revoke_client' => 'clients#revoke', as: :revoke_client
  get 'reactivate_client' => 'clients#reactivate', as: :reactivate_client

  resources :clients, only: [:index, :create, :new, :destroy]
  resources :events, only: [:index, :create, :new, :destroy]
  resources :users, only: [:create, :new, :update]
  resources :admins, only: [:index]

  # API routes
  namespace :api do
    namespace :v1 do
      post '/auth' => 'sessions#auth'

      resources :salaries, only: [:index, :show, :create, :update, :destroy] do
        resources :tags, only: [:index]
        resources :locations, only: [:index]
      end

      resources :tags, only: [:index, :show, :create] do
        resources :salaries, only: [:index]
      end

      resources :locations, only: [:index, :show, :create] do
        resources :salaries, only: [:index]
      end

      resources :resource_owners, only: [:index, :show, :create] do
        resources :salaries, only: [:index]
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<div id="footer" class="container">
  <p>Applikation skapad av Lisa Westlund, som en uppgift i kursen Webbramverk vid Linnéuniversitetet</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>API</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> container">
      <p><%= value %></p>
    </div>
  <% end %>

  <div class="container">
    <% if !@current_user.nil? %>
      <nav class="navbar navbar-default">
        <ul class="nav navbar-nav" id="menu">
          <li><%= link_to 'Applikationer', clients_path %></li>
          <% if @current_user.role_id == 2 %>
          <li><%= link_to 'Admin', admins_path %></li>
          <% end %>
        </ul>
        <div class="navbar-right" id="user-information">
          <p>Inloggad som: <%= @current_user.username %></p>
          <%= link_to 'Logga ut', logout_path, method: :delete, data: {no_turbolink: true} %>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>